[dependencies]
  regex = "1"

[package]
  authors = ["Kevin Amado <kamadorueda@gmail.com>"]
  description = "Rust library for rich text and beautiful formatting in the terminal"
  edition = "2018"
  license = "MIT"
  name = "modern-terminal"
  repository = "https://github.com/kamadorueda/modern-terminal"
  version = "0.2.0"
